### ISSUE TITLE
Throws Key Error while running the chat

### ISSUE THREAD

**Issue by prakashgowinji** [heroku-examples/python-websockets-chat#12]
Here is the error log: 

Traceback (most recent call last):
  File "chat.py", line 17, in <module>
    REDIS_URL = os.environ['REDIS_URL']
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/UserDict.py", line 40, in __getitem__
    raise KeyError(key)
KeyError: 'REDIS_URL'

**Comment by kennethreitz** [comment]
You need to add the redis addon.
